### ISSUE TITLE
SQL file for Controller database setup

### ISSUE THREAD

**Issue by SylviaEngmann** [WaverleyLabs/fwknop#4]
The sdp.sql file needed for the database setup for the controller module cannot be found in the repo. Kindly assist.

**Comment by hydrolucid** [comment]
Hi Sylvia. The controller is an entirely separate repo and contains the sdp.sql file you're looking for: [https://github.com/WaverleyLabs/SDPcontroller](https://github.com/WaverleyLabs/SDPcontroller)
